### PR TITLE
Updating how ISR notifies task

### LINKED ISSUE #7: Interupt should use task notification
Unblocking a task isn't recommended way of handling things.

Free RTOS docs on what to do:

https://www.freertos.org/Documentation/02-Kernel/02-Kernel-features/03-Direct-to-task-notifications/03-As-counting-semaphore

### PR DESCRIPTION
**Pull request by larryk3**
- Toggling pins in ISR & adc task for debug
- Changed how ISR notifies task. Fixes #7 
- Split the task into reading ADC & a task that calls the BLE `notify()` function
- Changed nimble log level so it doesn't write to serial on every notify. This should speed things up a bit.

### CODE REVIEW

**Comment by dl-dl** [comment]
[Deferred Interrupt Handling](https://www.freertos.org/Documentation/02-Kernel/02-Kernel-features/11-Deferred-interrupt-handling#:~:text=Deferred%20interrupt%20processing%20will%20typically,rather%20than%20within%20the%20ISR.)

[RTOS task notifications](https://www.freertos.org/Documentation/02-Kernel/02-Kernel-features/03-Direct-to-task-notifications/03-As-counting-semaphore)

===============
[Task Priorities](https://www.freertos.org/Documentation/02-Kernel/02-Kernel-features/01-Tasks-and-co-routines/03-Task-priorities#task-priorities)

**Comment by larryk3** [comment]
Debugging why the task takes too long and some ISRs are missed
Typical ISR takes 7us, and the task runs after 14us.
Every ~5th task takes too long.

image

**Comment by larryk3** [comment]
No printing, things look fine

ISR takes 7.1us
ISR to task latency 25us
task duration 56 us

image

**Comment by larryk3** [comment]
DRDY down (adc has value) to CS up (finished reading values is at worse 225us (from a couple of runs)

image

**Comment by larryk3** [comment]
It goes up even more on occasion - 255 a couple of time

**Comment by larryk3** [comment]
Note, this is without an active BT connection

**Comment by larryk3** [comment]
With a BT connection, there are occasional skips

image

**Comment by larryk3** [comment]
```
pCharacteristic->setValue(batch, bytesRead);
digitalWrite(PIN_DEBUG_ADC_TASK, HIGH);
pCharacteristic->notify();
digitalWrite(PIN_DEBUG_ADC_TASK, LOW);
```

Notify call takes a long time

image

**Comment by larryk3** [comment]
Reducing the nimble log level from `log` to `warning` stops the print on every notify. This makes the `notify()` function call almost 2x faster.

**Comment by dl-dl** [comment]
try
size_t bytesRead = xStreamBufferReceive(xStreamBuffer, batch, sizeof(batch), 0);
instead of 
size_t bytesRead = xStreamBufferReceive(xStreamBuffer, batch, sizeof(batch), portMAX_DELAY);

Should have no negative effect now.

**Pull request merged**
